### ISSUE TITLE
[bug] Problem with how arrays are initialized 

### ISSUE THREAD

**Issue by steveruizok** [dai-shi/valtio-yjs#11]
See this project: https://codesandbox.io/s/valtio-yjs-demo-forked-1h97r?file=/src/App.js

I'm not sure what's happening, but I believe that passing a state initialized with an object that includes an array will cause a crash.

**Comment by dai-shi** [comment]
Thanks for reporting. Oh, the array items are duplicated. Is this what you mean by crash?

<img width="546" alt="image" src="https://user-images.githubusercontent.com/490574/136713744-6f5b50ab-69b5-466e-ba11-59f74f00947e.png">

**Comment by dai-shi** [comment]
If so, maybe it's related with #5 (#4).

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/valtio-yjs/v/0.1.3
Sorry for the delay.
