### ISSUE TITLE
don't sync values which are `ref`'d

### ISSUE THREAD

**Issue by BrianHung** [dai-shi/valtio-yjs#21]
Right now, in `setPValueToY` and `insertPValueToY` from `bindProxyAndYMap` and `bindProxyAndYArray` [functions](https://github.com/dai-shi/valtio-yjs/blob/main/src/index.ts) respectively, it's not checked that a value stored in valtio (a "p" value) is `ref`'d.

As a result, non-proxied objects are subscribed to, resulting in an error within `subscribe`

```
Uncaught TypeError: Cannot read properties of undefined (reading 'add')
proxyObject[LISTENERS].add(listener);
```

Expected behavior is that values which are `ref'd` (`refSet.has(value) === true`) should be excluded from syncing.

**Comment by dai-shi** [comment]
Thanks for reporting. It's not only for ref'd objects, but also for unsupported objects like `Map`. We can use `getVersion` to check if an object is a proxy or not.

**Comment by dai-shi** [comment]
Can you test with #23?
https://ci.codesandbox.io/status/dai-shi/valtio-yjs/pr/23
See "Local Install Instructions" ☝️

**Comment by BrianHung** [comment]
#23 fixes the issue with objects that are wrapped in `ref`. 

I'm running into a separate issue now with having a function in a `setPValueToY`. Would it be possible to use `!getVersion` as opposed to `isNonProxyObject`?

```diff
import { proxy, subscribe, getVersion } from 'valtio/vanilla';
- const isNonProxyObject = (x: unknown) => isObject(x) && getVersion(x) === undefined;
+ const isNotProxied = (x: unknown) => !getVersion(x)
```

From [valtio](https://github.com/pmndrs/valtio/blob/main/src/vanilla.ts)

```js
export function getVersion(proxyObject: unknown): number | undefined {
  return isObject(proxyObject) ? (proxyObject as any)[VERSION] : undefined
}
```

My specific use case if it helps is

```js
const state = proxy(new State({
  r: ref(...),
  f(this: State) {
    ...
  },
})
```

#23 takes care of `r` but `f` results in

```js
        throw new Error('unsupported p type');
```

Maybe it'd also be better to have

```js
  if (__DEV__) {
    console.warn('Please use proxy object')
  }
```

instead of throwing an error. Thoughts?

**Comment by dai-shi** [comment]
Yeah, but now I feel a bit worried about this change overall. I'm not 100% sure if there's anything unexpected can happen with ref'd objects and functions as well. So, I'd like to add the warning to ref'd objects too...

**Comment by BrianHung** [comment]
Setting a warning for objects which aren't synced while in development mode sounds intuitive 👍 . It'll match [valtio](https://github.com/pmndrs/valtio/commit/ac945d17e47e128918873d2351f4c595b6c7514d).

**Comment by dai-shi** [comment]
#23 is updated.

**Comment by BrianHung** [comment]
That works for me! Thanks for the quick responses.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/valtio-yjs/v/0.3.1
