### ISSUE TITLE
Simple unified api?

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/valtio-yjs#3]
Current:
```js
import { bindProxyAndYMap, bindProxyAndYArray } from 'valtio-yjs';

bindProxyAndYMap(objProxy, ymap);
bindProxyAndYArray(arrProxy, yarray);
```

Proposal:
```js
import { bind } from 'valtio-yjs';

bind(objProxy, ymap);
bind(arrProxy, yarray);
```

**Comment by cqh963852** [comment]
While bind a proxy and yValue,  If there is a difference in the data between them, how should one choose?

Such as 
proxy: 
```
{
"a":"a"
}
```

yMap
```
Map({
"b":"b"
})
```

I tend the default behavior is to merge the data from both. But there keep a user-defined way.

**Comment by dai-shi** [comment]
I think merging `{"a":"a"}` and `{"b":"b"}` is easy. Merge from both.
What would be difficult is `{"a":"a"}` and `{"a":undefined}`.
I would prioritize yjs to proxy, because yjs is closer to backend.
My preference is not to have an option for this, but it can't be helped with certain use cases. Do you see any use case where you need to prioritize proxy to yjs?
