### ISSUE TITLE
unsupported type p

### ISSUE THREAD

**Issue by wmonecke** [dai-shi/valtio-yjs#6]
Hi!

I am getting stuck and hitting a wall. Maybe I have just been working for too long.

`````

  useEffect(() => {
    const websocketProvider = new WebsocketProvider(
      "ws://localhost:1234",
      project.id,
      ydoc.current
    )
    websocketProvider.on("status", (event) => {
      console.log(event.status) // logs "connected" or "disconnected"
    })
    const ymap = ydoc.current.getMap(`kanban.${project.id}`)
   
    const stateProxy = proxy({ ...project })

    bindProxyAndYMap(stateProxy, ymap)
   
  }, [])
`````

`bindProxyAndYMap(stateProxy, ymap)` is throwing an error `unsupported type p`. `project` is an object with nested objects and arrays.

Any ideas what I can be doing wrong?

**Comment by dai-shi** [comment]
https://github.com/dai-shi/valtio-yjs/blob/dc6d33bc7b14dcc2924c622f7d4021474523b3da/src/index.ts#L53-L55

These are only supported primitive types. Does `project` have something else?

**Comment by wmonecke** [comment]
I guess objects with nested arrays arent support :(

**Comment by dai-shi** [comment]
It should, but there can be a bug. Could you create a small reproduction please?

**Comment by dai-shi** [comment]
@wmonecke Are you still around? We hope #10 solve your issue. Would you like to try?

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/valtio-yjs/v/0.1.2 is published.
Let me close this for now. If the problem persists, feel free to let us know and we will re-open.
