### ISSUE TITLE
`null` not supported

### ISSUE THREAD

**Issue by mattrossman** [dai-shi/valtio-yjs#9]
When the state includes a `null` value, valtio-yjs throws an error:

```
Uncaught Error: unsupported p type
```

I encountered this when trying to synchronize an array of excalidraw elements between clients, which often contain a null boundElementIds property.

Possibly the cause of #6

**Comment by dai-shi** [comment]
Oh, nice catch!!
Would you like to draft a PR and test it?
I think it's just adding `pv === null ||`, if yjs supports `null`.
